version: "3.6"

services:
  # PostgreSQL Server for Keycloak
  pg_keycloak:
    image: postgres:12
    networks:
      - demo-network
    volumes:
      - pg_keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always

  # Keycloak
  keycloak:
    build: ./keycloak
    ports:
      - "8081:8080"
    networks:
      - demo-network
    depends_on:
      - pg_keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: pg_keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    restart: always

  # PostgreSQL Server for Hasura
  pg_hasura:
    image: postgres:12
    networks:
      - demo-network
    volumes:
      - pg_hasura_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    restart: always

  # Hasura
  hasura:
    image: hasura/graphql-engine:v2.0.3
    ports:
      - "8080:8080"
    depends_on:
      - pg_hasura
      - keycloak
    networks:
      - demo-network
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@pg_hasura:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"jwk_url": "http://keycloak:8080/auth/realms/hasura/protocol/openid-connect/certs"}'
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    restart: always

volumes:
  pg_hasura_data:
  pg_keycloak_data:
networks:
  demo-network:
